version: '3.8'

services:
  web:
    image: php:8.3-apache
    container_name: web
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - bridge


  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mon_site
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - monreseau

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-cont
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: pass
    depends_on:
      - db
    networks:
      - monreseau

volumes:
  mariadb_data:

networks:
  monreseau:
